db:
  username: ${username.value:postgres}
  password: pass
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost,127.0.0.1
  properties:
    first: 123
    second: 567
    third.value: Third
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 2
    - size: 2
      timeout: 3
    - size: 3
      timeout: 9

logging:
  level:
    root: INFO
    com.dmdev.spring.database.pool.ConnectionPool: info
    org.springframework.jdbc.core: trace
  file:
    name: dmdev.log
    path: /

spring.profiles.active: qa

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2dll.auto: validate
    #      on Hibernate level
    #      batch_size: 50
    #      fetch_size: 50
    open-in-view: false
  mvc:
  #    # first var decide problem with convert date from string in MVC test
  #    format:
  #      date: iso
  #      date-time: iso
  #      time: iso

  #    view:
  #      prefix: /WEB-INF/jsp/
  #      suffix: .jsp
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 1057504398138-n9nnnh1g8mu0jflune6vkm4a0c3div9t.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: http://localhost:8080/login/oauth2/code/google
            scope: openid,email,profile

  messages:
    basename: messages

spring.liquibase.change-log: classpath:db/changelog/db.chagelog-master.yaml



springdoc:
  swagger-ui:
    oauth:
      client-id: 1057504398138-n9nnnh1g8mu0jflune6vkm4a0c3div9t.apps.googleusercontent.com
      client-secret: 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
      scope: openid,email,profile
      oauth2-redirect-url: http://localhost:8080/swagger-ui/oauth2-redirect.html
app:
  common:
    logging:
      level: INFO
      enable: true